name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  google_sign_in: ^7.2.0
  cloud_firestore: ^6.1.0
  provider: ^6.1.2
  go_router: ^17.0.0
  multi_select_flutter: ^4.1.3
  intl: ^0.20.2
  google_fonts: ^6.3.2
  flutter_svg: ^2.0.10+1
  flutter_colorpicker: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/avatars/
    - assets/avatar_layers/base/
    - assets/avatar_layers/hair/
    - assets/avatar_layers/beard/
